name: ci

on:
  push:
    path: 
      - README.md
      - .github/workflows/ci.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: python-node.Dockerfile
          push: true
          tags: unkn0wn876/python3.8-nodejs14:latest


      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4 # v4.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: unkn0wn876/python3.8-nodejs14
          short-description: "Last updated by bot on $(date)"