name: ci

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: python-node.Dockerfile
          push: true
          tags: unkn0wn876/python3.8-nodejs14:latest

  description:
    name: Update versions.json and README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Update README.md
        run: |
              git config --global user.name "UnknOwnkisuke" > /dev/null 2>&1
              git config --global user.email phenix_jop@live.com > /dev/null 2>&1

              # Update README.md
              today=$(date +%Y-%m-%d)
              sed -i -E "s/Last updated by bot: .*/Last updated by bot: ${today}/" README.md

              git add README.md
              git commit -m '🗃 Updated python/node versions [skip ci]'
              git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Unkn0wnKisuke/docker-custom-images.git HEAD:main --quiet