name: ci

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: python-node.Dockerfile
          push: true
          tags: unkn0wn876/python3.8-nodejs14:latest

  description:
    name: Update versions.json and README.md
    runs-on: ubuntu-latest
    steps:



      - uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull --quiet origin main

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: unkn0wn876/python3.8-nodejs14         
             

    